name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "hotfix/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --verbose
      - name: Cargo fmt check
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads 4
